on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Run deploy script
        run: ./deploy.sh
        shell: bash
